lib/copy.js
package.json
test/copy.tilelive.test.js

Pyramid copy for raw data

---

package.json

Tilelive 5.5.x

---

bin/mapbox-tile-copy.js
test/executable.test.js

Add interval flag

---

bin/mapbox-tile-copy.js
test/executable.test.js

- clarification of arg parsing logic
- if an interval is set, don't `\r\033[K` to rewrite the existing line
- if logging at all, always send a final report

Logging adjustments

---

package.json

Ref https://github.com/mapbox/unpacker/issues/405

Add mapnik-omnivore refactor

---

package.json

Ref https://github.com/mapbox/unpacker/issues/415

Update for maxzoom bug fix in mapnik-omnivore

---

package.json

Loosened Mapnik dependency to reduce tagging parties

---

package.json

Avoid buggy Mapnik 3.3.0 and update to newest mapnik-omnivore.

Avoid dupes

---

package.json

Per https://github.com/mapbox/tilelive-s3/pull/48 
cc @rclark

NAN port + aws-sdk

---

package.json

Per https://github.com/mapbox/unpacker/pull/619

mapnik 3.4.6 and protozero update

---

lib/tilelivecopy.js
test/executable.test.js

Per https://github.com/mapbox/unpacker/issues/561#issuecomment-147818065
cc @rclark @yhahn

Rely on tilelive to close

---

package.json
test/executable.test.js

And a few fixes for test fails in master from updated deps.

Use tilelive-s3@3.1.0

---

package.json

Reverse https://github.com/mapbox/mapbox-tile-copy/commit/bbfab1a43b62675e6614e81d871728dd795590b4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R32
Also solves https://github.com/mapbox/mapbox-tile-copy/pull/44/files
cc @yhahn @jakepruitt

Allow automatic Minor updates

---

package.json

Per https://github.com/mapbox/mapbox-upload-validate/pull/53

Bump validation

---

lib/tilelivecopy.js
test/copy.tilelive.test.js

Adds v2 tile migration for tilejson copy jobs.
cc/ @mapsam @ajashton @springmeyer

Tilejson migration

---

.travis.yml

Should be able to pass on node4
fixes #66

Ask travis to test node 4

---

readme.md

It wasn't on the README before.

Add installation step

---

.travis.yml
test/copy.tilelive.test.js

@GretaCB this fixes the signature failure that you were seeing in tests using the most recent aws-sdk.

Specify region when listing tiles during tests

---

CHANGELOG.md
lib/get-uri.js
package.json

Running into git sha errors with yarn, making a second branch for testing.
https://github.com/mapbox/mapbox-tile-copy/pull/94

Nom nom two

---

package.json

refs: https://github.com/mapbox/tilelive-bridge/pull/92
cc @springmeyer @GretaCB

use tilelive-bridge to log maximum tile size stats

---

package.json
test/copy.tilelive.test.js
test/executable.test.js

Per https://github.com/mapbox/mapnik-omnivore/pull/172, update tests
cc @mapbox/unpacker

Minzoom to z0 for <10mb files

---

.travis.yml
package-lock.json
package.json
test/index.test.js

fixes #136
* impl. routine to clean files from s3 after tests complete

Implement S3 Cleanup Routine

---

.travis.yml
package-lock.json
package.json

Upgrade mbtiles to 0.10.0
